#!/usr/bin/perl -w
#
# Check to see whether the current architecture is supported
# (MacOS x86_64)

# Determine OS type

my $os = `uname -s 2>/dev/null`;
chomp $os;

# Determine whether the arch is supported

my $supported = 'N';

if($os eq 'Darwin') {

    my $sysctl_data = `sysctl -n hw.cpu64bit_capable`;
    chomp $sysctl_data;

    if($sysctl_data eq '1') {
	$supported = 'Y';
    }
    else {
	$supported = 'N';
    }

}

# Output the result

print "$supported\n";

exit 0;
