#!/bin/sh
#
# Link script for cblas

if [ -n "@SDK_MATH_SLOT@" ]; then
    EXEC=@SDK_ROOT@/math-slots/@SDK_MATH_SLOT@/bin/cblas_link
else
    EXEC=@SDK_ROOT@/math-slots/default/bin/cblas_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate slot link script for cblas"
    exit 1
fi
