#!/bin/bash
#
# Script to relocate an ELF binary so that all internal paths are
# relative to a given base directory. Requires the patchelf utility
# to be somewhere in the PATH

FILE=$1
BASE=$2

# Check arguments

if [[ -z $FILE ]]; then
    echo "No FILE specified"
    exit 1
fi

if [[ -z $BASE ]]; then
    echo "No BASE specified"
    exit 1
fi

# Check if FILE is a file (this weeds out symlinks etc)

if [ -f $FILE ]; then

    # Check if the file is ELF format

    if `file $FILE | grep -q 'ELF'`; then

	# Check that the file has a dynamic section

	if `readelf -d $FILE | grep -q 'Dynamic'`; then

	    FD=`dirname $FILE`

	    # Fix the rpath
	    
	    rpath_old=`patchelf --print-rpath $FILE | awk -v repl=$FD '{
  gsub(/\\$ORIGIN/, repl); print
}'`

            rpath_new=`relpath $rpath_old $FD | awk -F: '{
  for (i = 1; i <= NF; i++) {
    if ($i == ".")
      $i = "$ORIGIN"
          else
      $i = "$ORIGIN/" $i
  }
  OFS=":"
  print
}'`

            patchelf --set-rpath $rpath_new $FILE --shrink-rpath

	fi

    fi
    
fi
