#!/bin/bash
#
# Script to relocate an ELF binary so that all internal paths are
# relative to a given base directory

FILE=$1
BASE=$2

# Check arguments

if [[ -z $FILE ]]; then
    echo "No FILE specified"
    exit 1
fi

if [[ -z $BASE ]]; then
    echo "No BASE specified"
    exit 1
fi

# Check if FILE is a file (this weeds out symlinks etc)

if [ -f $FILE ]; then

    # Check if the file is ELF format

    if `file $FILE | grep -q '/ELF/'`; then

	# Check that the file has a dynamic section

	if `readelf -d $FILE | grep -q '/Dynamic/'`; then

	    file_name=`basename $FILE`
	    file_dir=`dirname $FILE`

	    # Fix the rpath
	    
	    rpath_old=`patchelf --print-rpath $FILE | sed -e "s|\\$ORIGIN|$file_dir|g"`
            rpath_new=`relpath $rpath_old $file_dir | sed -e "s|^|\\$ORIGIN/|" -e "s|:|:\\$ORIGIN/|g"`

            patchelf --set-rpath $rpath_new $file --shrink-rpath

	fi

    fi
    
fi
