#!/usr/bin/env python3
#
# Convert absolute paths to relative

import os.path as op
import sys

abs_paths = sys.argv[1].split(':')
base_path = sys.argv[2]

rel_paths = []

for abs_path in abs_paths:
    rel_paths += [op.relpath(abs_path, base_path)]

print(':'.join(rel_paths))
