#!/bin/bash
#
# Script to sign a file

FILE=$1
ENTITLE_FILE=$2

# Check SDK2_CDS_CERT_NAME is set

if [[ -z $SDK2_CDS_CERT_NAME ]]; then
    echo "Environment variable SDK2_CDS_CERT_NAME is not set"
    exit 1
fi

# Check SDK2_CDS_CERT_PATH is set

if [[ -z $SDK2_CDS_CERT_PATH ]]; then
    echo "Environment variable SDK2_CDS_CERT_PATH is not set"
    exit 1
fi

# Check if FILE is a file (this weeds out symlinks etc)

if [ -f $FILE ]; then

    # Check if the file is Mach-O format

    if `file $FILE | grep -q 'Mach-O'`; then

        # Check that the file is of the appropriate type

        if `file $FILE | egrep -q 'executable|library|bundle'`; then

	    # Go ahead and sign

	    if [[ -n $ENTITLE_FILE ]]; then
		codesign --force --options runtime --timestamp \
		    --entitlements $ENTITLE_FILE --deep \
		    --keychain "$SDK2_CDS_CERT_PATH" \
		    --sign "$SDK2_CDS_CERT_NAME" \
		    $FILE
	    else
		codesign --force --options runtime --timestamp \
		    --deep \
		    --keychain "$SDK2_CDS_CERT_PATH" \
		    --sign "$SDK2_CDS_CERT_NAME" \
		    $FILE
	    fi

	fi
    fi
fi
