#!/usr/bin/perl -w
#
# Check to see whether the current architecture is supported

# Determine OS type

my $os = `uname -s 2>/dev/null`;
chomp $os;

# Determine whether the arch is supported

my $supported = 'N';

if($os eq 'Linux') {

    # Linux -- use uname -m

    my $arch = `uname -m 2>/dev/null`;
    chomp $arch;

    my $verstr = `uname -r 2>/dev/null`;
    chomp $verstr;

    if($arch eq 'x86_64') {
	$supported = 'Y';
    }
    elsif($arch eq 'i686') {
	$supported = 'Y';
    }
    
    if($verstr =~ /Microsoft/){
	$supported = 'N';
    }

}
elsif($os eq 'Darwin') {

    # Darwin (OS X) -- use sysctl (on some systems uname -m returns
    # i386 even though 64-bit userspace progs are fine)

    my $sysctl_data = `sysctl -n hw.cpu64bit_capable`;
    chomp $sysctl_data;

    if($sysctl_data eq '1') {
	$supported = 'Y';
    }
    else {
	$supported = 'N';
    }

}

# Output the result

print "$supported\n";

exit 0;
