#!/bin/sh
#
# Link script for virtual_lapack95

if [ -n "@SDK_MATH_SLOT@" ]; then
    EXEC=@SDK_ROOT@/math-slots/@SDK_MATH_SLOT@/bin/lapack95_link
else
    EXEC=@SDK_ROOT@/math-slots/default/bin/lapack95_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate slot link script for lapack95"
    exit 1
fi
