# Base system

FROM centos:6.10

# Metadata

MAINTAINER NAME townsend@astro.wisc.edu

# Add user

RUN grep -q :@GROUP_ID@: /etc/group || groupadd --gid @GROUP_ID@ user
RUN useradd --uid @USER_ID@ --gid @GROUP_ID@ -m user

# Get yum working again

# Set path to the centos vault

RUN sed -i -e 's/^#baseurl=/baseurl=/' \
           -e 's/^mirrorlist=/#mirrorlist=/' \
           -e 's!http://mirror.centos.org/centos/$releasever/!http://vault.centos.org/6.10/!' \
           /etc/yum.repos.d/*.repo

# Disable auto mirror selection

RUN sed -i -e 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf

# Upgrade selinux-python

RUN rpm -ivh --nodeps http://vault.centos.org/6.10/os/x86_64/Packages/libselinux-python-2.0.94-7.el6.x86_64.rpm
RUN yum -y clean all

# Tell yum not to install 32-bit packages

RUN echo "multilib_policy=best" >> /etc/yum.conf

# Install basic developer tools

RUN yum -y install \
    curl make patch m4 bzip2 texinfo \
    binutils glibc-devel glibc-static \
    perl libX11-devel file \
    zlib-devel nano tcsh which

# Install newer automake & autoconfig (needed to compile tar)

RUN curl http://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz -O
RUN tar xf autoconf-2.72.tar.gz
RUN cd autoconf-2.72 && \
    ./configure --prefix=/usr/local && \
    make -j && make install
RUN rm -r autoconf-2.72.tar.gz autoconf-2.72

RUN curl http://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.gz -O
RUN tar xf automake-1.16.5.tar.gz
RUN cd automake-1.16.5 && \
    ./configure --prefix=/usr/local && \
    make -j && make install
RUN rm -r automake-1.16.5.tar.gz automake-1.16.5

# Install bootstrap tools

RUN mkdir /opt/bootstrap
WORKDIR /opt/bootstrap

RUN curl http://user.astro.wisc.edu/~townsend/resource/download/mesasdk/mesasdk-x86_64-linux-23.7.3.tar.gz -O
RUN tar xf mesasdk-x86_64-linux-23.7.3.tar.gz
ENV MESASDK_ROOT=/opt/bootstrap/mesasdk
RUN . ${MESASDK_ROOT}/bin/mesasdk_init.sh
RUN rm mesasdk-x86_64-linux-23.7.3.tar.gz

# Set the root password

RUN echo 'root:Docker!' | chpasswd

# Reset WORKDIR

WORKDIR /home/user
