# syntax=docker/dockerfile:1
# check=skip=SecretsUsedInArgOrEnv

# Base system

FROM redhat/ubi9

# Metadata

LABEL org.opencontainers.image.authors="townsend@astro.wisc.edu"

# Register, attach subscription, and enable required repositories
RUN --mount=type=secret,id=rh_username,env=RH_USERNAME \
    --mount=type=secret,id=rh_password,env=RH_PASSWORD \
    subscription-manager register --username "$RH_USERNAME" --password "$RH_PASSWORD" --auto-attach \
    && dnf repolist \
    && dnf config-manager --set-enabled codeready-builder-for-rhel-9-`uname -m`-rpms

# If necessary, add a user

RUN grep -q :@GROUP_ID@: /etc/group || groupadd --gid @GROUP_ID@ user
RUN grep -q :@USER_ID@: /etc/passwd || useradd --uid @USER_ID@ --gid @GROUP_ID@ -m user

# Add the EPEL repository

RUN dnf -y install \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

# Install basic developer tools

RUN dnf -y install \
    make patch m4 bzip2 xz tcsh texinfo \
    binutils glibc-devel glibc-static \
    perl-core libX11-devel file \
    zlib-devel nano diffutils patchelf \
    meson

# Install newer automake & autoconfig (needed to compile tar)

RUN curl https://mirrors.ocf.berkeley.edu/gnu/autoconf/autoconf-2.72.tar.gz -O
RUN tar xf autoconf-2.72.tar.gz
RUN cd autoconf-2.72 && \
    ./configure --prefix=/usr/local && \
    make -j && make install
RUN rm -r autoconf-2.72.tar.gz autoconf-2.72

RUN curl https://mirrors.ocf.berkeley.edu/gnu/automake/automake-1.16.5.tar.gz -O
RUN tar xf automake-1.16.5.tar.gz
RUN cd automake-1.16.5 && \
    ./configure --prefix=/usr/local && \
    make -j && make install
RUN rm -r automake-1.16.5.tar.gz automake-1.16.5

# Set the root password

RUN echo 'root:Docker!' | chpasswd
