#!/bin/sh
#
# Launch an SDK2 docker container

### VALIDATION ###

# Check SDK2_ROOT is set and valid

if [[ -z $SDK2_ROOT ]]; then
    echo "Environment variable SDK2_ROOT is not set"
    exit 1
fi

if [[ ! -d $SDK2_ROOT ]]; then
    echo "Root directory '$SDK2_ROOT' is missing"
    exit 1
fi

# Check SDK2_TMP is set and valid

if [[ -z $SDK2_TMP ]]; then
    echo "Environment variable SDK2_TMP is not set"
    exit 1
fi

if [[ ! -d $SDK2_TMP ]]; then
    echo "Root directory '$SDK2_TMP' is missing"
    exit 1
fi

# Launch the session

C_SDK2_ROOT=/home/user/sdk2
C_SDK2_TMP=/home/user/sdk2-tmp

docker run -it --rm \
       --env SDK2_ROOT=$C_SDK2_ROOT \
       --env SDK2_TMP=$C_SDK2_TMP \
       --env SDK2_PROFILE --env SDK2_RELEASE \
       --mount type=bind,readonly,source=$SDK2_ROOT,target=$C_SDK2_ROOT \
       --mount type=bind,source=$SDK2_TMP,target=$C_SDK2_TMP \
       sdk2_build bash
