#!/bin/sh
#
# Link script for  xblas

if [ -n "@SDK_MATH_SLOT@" ]; then
    EXEC=@SDK_ROOT@/math-slots/@SDK_MATH_SLOT@/bin/xblas_link
else
    EXEC=@SDK_ROOT@/math-slots/default/bin/xblas_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate slot link script for xblas"
    exit 1
fi
