#!/bin/sh
#
# Link script for virtual_lapack

if [ -n "@SDK_MATH@" ]; then
    EXEC=@SDK_ROOT@/bin/math/@SDK_MATH@/lapack_link
else
    EXEC=@SDK_ROOT@/bin/math/default/lapack_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate link script for lapack"
    exit 1
fi
