#!/usr/bin/env bash

### VALIDATION ###

# Check SDK2_TMP is set and valid

if [[ -z $SDK2_TMP ]]; then
    echo "Environment variable SDK2_TMP is not set"
    exit 1
fi

if [[ ! -d $SDK2_TMP ]]; then
    echo "Temporary directory '$SDK2_TMP' is missing"
    exit 1
fi

# Check SDK2_RELEASE is set

if [[ -z $SDK2_RELEASE ]]; then
    echo "Environment variable SDK2_RELEASE is not set"
    exit 1
fi

# Check SDK2_NUSER is set

if [[ -z $SDK2_NUSER ]]; then
    echo "Environment variable SDK2_NUSER is not set"
    exit 1
fi

### VARIABLES ###

# Define standard directories

export SDK2_PKG_ROOT=${SDK2_TMP}/pkg

### ACTION ###

# Submit for notarization

xcrun altool --notarize-app \
             --primary-bundle-id "edu.wisc.astro.pkg.mesasdk" \
             --username "$SDK2_NUSER" \
	     --password "@keychain:AC_PASSWORD" \
             --file ${SDK2_PKG_ROOT}/mesasdk-x86_64-macos-$SDK2_RELEASE.pkg
