#!/usr/bin/env bash
#
# Post-installation script for MESA SDK

export MESASDK_ROOT=/Applications/mesasdk

# Create sysroot symlink

os_ver=$(sw_vers -productVersion)

major=$(echo "$os_ver" | awk -F. '{ print $1; }')
minor=$(echo "$os_ver" | awk -F. '{ print $2; }')

case $major in

    10)

	case $minor in
	    10|11|12|13)
		sysroot='/'
		;;
	    14|15)
		sysroot='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
		;;
	    *)
		echo "Invalid OS minor version number: $minor"
		exit 1
		;;
	esac
	;;

    11|12|13|14|15)

	sysroot='/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
	;;

    *)
	
	echo "Invalid OS major version number: $major"
	exit 1
	;;

esac

if [[ ! -e $sysroot ]]; then
   osascript <<-EndOfScript
display dialog "Error locating Xcode command-line tools" buttons {"OK"} default button 1 with icon caution with title "Install MESA SDK"
EndOfScript
   exit 1
fi

if [[ -L $sysroot ]]; then
    sysroot=`dirname $sysroot`/`readlink $sysroot`
fi

rm -f ${MESASDK_ROOT}/sysroot
ln -s $sysroot ${MESASDK_ROOT}/sysroot

# Regenerate headers

mkheaders=$(find "$MESASDK_ROOT/" -name mkheaders | head -n 1)
$mkheaders "$MESASDK_ROOT"

if [ $? != 0 ]; then
   osascript <<-EndOfScript
display dialog "Error regenerating compiler headers" buttons {"OK"} default button 1 with icon note caution title "Install MESA SDK"
EndOfScript
    exit 1
fi

exit 0
