#!/bin/bash

# Check SDK2_RELEASE is set

if [[ -z $SDK2_RELEASE ]]; then
    echo "Environment variable SDK2_RELEASE is not set"
    exit 1
fi

# Customize the template pkproj file

pkgproj_file=$(mktemp mesasdk.XXXXXX)

sed -e "s/@RELEASE@/$SDK2_RELEASE/g" mesasdk.template.pkgproj > $pkgproj_file

# Build the project

/usr/local/bin/packagesbuild --verbose $pkgproj_file

# Finish

rm $pkgproj_file

