#!/usr/bin/env bash

### VALIDATION ###

# Check SDK2_TMP is set and valid

if [[ -z $SDK2_TMP ]]; then
    echo "Environment variable SDK2_TMP is not set"
    exit 1
fi

if [[ ! -d $SDK2_TMP ]]; then
    echo "Temporary directory '$SDK2_TMP' is missing"
    exit 1
fi

# Check SDK2_RELEASE is set

if [[ -z $SDK2_RELEASE ]]; then
    echo "Environment variable SDK2_RELEASE is not set"
    exit 1
fi

# Check SDK2_NUSER is set

if [[ -z $SDK2_NUSER ]]; then
    echo "Environment variable SDK2_NUSER is not set"
    exit 1
fi

### VARIABLES ###

# Define standard directories

export SDK2_PKG_ROOT=${SDK2_TMP}/pkg

### ACTION ###

# Submit for notarization

pkg_file=${SDK2_PKG_ROOT}/mesasdk-aarch64-macos-$SDK2_RELEASE.pkg

xcrun notarytool submit $pkg_file \
      --apple-id "$SDK2_NUSER" \
      --team-id "$SDK2_NTEAM" \
      --keychain-profile notarization \
      --wait

stapler staple $pkg_file
