#!/bin/sh
#
# Link script for blas

if [ -n "@SDK_MATH_SLOT@" ]; then
    EXEC=@SDK_ROOT@/math-slots/@SDK_MATH_SLOT@/bin/blas_link
else
    EXEC=@SDK_ROOT@/math-slots/default/bin/blas_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate slot link script for blas"
    exit 1
fi
