#!/bin/sh
#
# Link script for virtual_lapack95

if [ -n "@SDK_MATH@" ]; then
    EXEC=@SDK_ROOT@/bin/math/@SDK_MATH@/lapack95_link
else
    EXEC=@SDK_ROOT@/bin/math/default/lapack95_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate link script for lapack95"
    exit 1
fi
