#!/bin/sh
#
# Link script for virtual_xblas

if [ -n "@SDK_MATH@" ]; then
    EXEC=@SDK_ROOT@/bin/math/@SDK_MATH@/xblas_link
else
    EXEC=@SDK_ROOT@/bin/math/default/xblas_link
fi

if [ -x "$EXEC" ]; then
    exec $EXEC
else
    echo "Unable to locate link script for xblas"
    exit 1
fi
